name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: 's0nnyhu'
        reponame: 's0nnyhu.github.io'
        token: ${{ secrets.GITHUB_TOKEN }}
